$(document).ready ->
  tasksUl = $('#user_tasks_bar')
  if tasksUl.length
    $.get tasksUl.data('url'), {}, (data) ->
      console.log 'Channels: ', data.channels
      _.each data.channels, (channel) ->
        q = new Queue2(tasksUl.data('host'), tasksUl.data('port'), '/ws')
        # подписка на канал
        q.subscribe channel
        return
      return
  return

# ---
# generated by js2coffee 2.1.0
