activePage = null
usersUrl = null

removeUser = (url) ->
  $.confirm
    text: 'Вы действительно хотите удалить пользователя?'
    confirm: (button) ->
      $.post url, { csrfmiddlewaretoken: csrftoken }, (data) ->
        window.location = data.redirect_url
        return
      return
    title: 'Удаление пользователя'
    confirmButton: 'Удалить'
    cancelButton: 'Отмена'
  return

prev = ->
  search = $('#search').val()
  activePage = if activePage == 0 then activePage else activePage - 1
  document.location = usersUrl + '?page=' + activePage + ';search=' + search
  return

next = ->
  search = $('#search').val()
  current = $('li.active[data-pagi=\'true\']')
  if !current.attr('data-max')
    activePage = activePage + 1
  document.location = usersUrl + '?page=' + activePage + ';search=' + search
  return

pagi = (ind) ->
  search = $('#search').val()
  document.location = usersUrl + '?page=' + ind + ';search=' + search
  return

search = ->
  `var search`
  search = $('#search').val()
  document.location = usersUrl + '?search=' + search
  return

$(document).ready ->
  activePage = $('#active_num').val()
  usersUrl = $('#users_table').attr('data-url')
  $('[name="birth_date"]').datepicker
    format: 'dd.mm.yyyy'
    autoclose: true
    forseParse: false
    keyboardNavigation: false
  $('[name="phone"]').inputmask '99999999999'
  return

# ---
# generated by js2coffee 2.1.0
