# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-06 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_auto_20160906_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cube',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='cube',
            name='user',
        ),
        migrations.RemoveField(
            model_name='datasettometa',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='datasettometa',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='datasourcesjournal',
            name='trigger',
        ),
        migrations.RemoveField(
            model_name='datasourcestrigger',
            name='datasource',
        ),
        migrations.RemoveField(
            model_name='dimension',
            name='datasources_meta',
        ),
        migrations.RemoveField(
            model_name='dimension',
            name='user',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='datasources_meta',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cube',
        ),
        migrations.DeleteModel(
            name='DatasetToMeta',
        ),
        migrations.DeleteModel(
            name='DatasourcesJournal',
        ),
        migrations.DeleteModel(
            name='DatasourcesTrigger',
        ),
        migrations.DeleteModel(
            name='Dimension',
        ),
        migrations.DeleteModel(
            name='Measure',
        ),
    ]
