# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-07 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20161006_1554'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datasourcemetakeys',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='datasourcemetakeys',
            name='meta',
        ),
        migrations.RemoveField(
            model_name='datasourcesettings',
            name='name',
        ),
        migrations.DeleteModel(
            name='DatasourceMetaKeys',
        ),
    ]
