# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-07 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20161007_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasourcesettings',
            name='name',
            field=models.IntegerField(choices=[(1, 'indent')], db_index=True, default=1, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
