# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-08 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_datasourcesettings_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='datasourcesettings',
            unique_together=set([('name', 'datasource')]),
        ),
    ]
