# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-10 06:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20161008_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Источник', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Datasource')),
                ('Хранилище', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Dataset')),
            ],
            options={
                'db_table': 'dataset_source',
            },
        ),
        migrations.RemoveField(
            model_name='columns',
            name='dataset',
        ),
        migrations.AlterField(
            model_name='columns',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DatasetSource', verbose_name='Источник хранилища'),
        ),
    ]
