# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-10 10:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20161008_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='context',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='', null=True),
        ),
    ]
