# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-10 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_auto_20161010_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='columns',
            name='default_val',
            field=models.IntegerField(choices=[(1, 'zero'), (2, 'remove')], default=1, verbose_name='Default value'),
        ),
    ]
