# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-10 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_columns_default_val'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columns',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
    ]
