# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-11 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20161010_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columns',
            name='type',
            field=models.CharField(choices=[(1, 'text'), (2, 'integer'), (3, 'double precision'), (4, 'timestamp'), (5, 'boolean')], default=1, max_length=20, verbose_name='Тип'),
        ),
    ]
